server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DmitrySkachkov10/JAVA1
          search-paths: 'Cloud/config-repo'
          clone-on-start: true
        bootstrap: true
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
